### ISSUE TITLE
Pin creation when sending normal messages

### ISSUE THREAD

**Issue by Bobins666** [Djidam/macro-talk#1] opened 2020-12-07 14:37 UTC
Heya, I'm kinda new to github and don't really get the pull request/comments thing and honestly I'm too tired to figure it out.

Anyway the solution to your problem with the constant pin creation is pretty simple.

Line 40:  return C_Map.GetUserWaypointHyperlink()

Change to:  return C_Map.GetUserWaypointHyperlink(), C_Map.ClearUserWaypoint()

It removes the pin after linking to chat (you don't need to keep your pin, or if you do you can just click your own link in chat to re-place the pin at your current location), from now on a pin wont be placed when you use a normal chat (or it's removed right away anyway thus not having a new pin randomly on the map)

Edit: However now we have the flip side, it removes a pin manually set when you send a normal chat message (that's fine for me, as I don't use manual pins very often anyway.) - it was late when figuring this out didn't do a lot of testing

**Comment by Djidam** [comment] 2020-12-08 00:09
Yeah, 

Didnt think of it, was to focused trying to stop it from creating a pin in the first place.
Your idea give me some hints, I have to try some things.

**Comment by Bobins666** [comment] 2020-12-08 04:53
Did a little more testing, Commented out the waypoint cmd and added print "test", when doing %wp command I get 2 test responsed, doing %loc and %sz I get one response, seems all other commands post one test response, something with the wp function is returning it twice and I can't figure out what lol, hope this helps.

**Comment by Djidam** [comment] 2020-12-08 16:35
Hmm could you past here the code of your test plz.

Do you get a "test" print with juste typing text in chat ?
You know maybe that is why I get a pin created every time a chat text is validated ?

**Comment by Bobins666** [comment] 2020-12-08 21:26
Yeah it was spitting out test when a normal chat was sent, so the double return isn't the issue just found it odd and couldn't figure it out myself, I think the issue is with the messaging trigger, but normally goes unnoticed because it doesn't actually send anything and I don't know enough about coding or LUA to see anything wrong (i've looked in the subs and other files but everything looks like it should be fine to me) 

	["%%[Ww][Pp]"] = function()
		local mapID = C_Map.GetBestMapForUnit("player")
		if mapID == nil then
			return;
		end
		local position = C_Map.GetPlayerMapPosition(mapID,"player")
		if not position then
		return;
		end
		print  "test" --C_Map.SetUserWaypoint(UiMapPoint.CreateFromCoordinates(mapID,position:GetXY()))
		--return C_Map.GetUserWaypointHyperlink(), C_Map.ClearUserWaypoint()
	end,

All I did was comment the set waypoint line and the return and added print "test" where the waypoint line is, I haven't tried putting the print elsewhere in the file and realms are down where I am atm.

**Comment by Bobins666** [comment] 2020-12-08 21:28
Have you reached out to cogwheel by email or anything? (not sure if he checks it or if he still plays the game or anything like that)

**Comment by Djidam** [comment] 2020-12-09 11:01
I didnt't try to reach him. I took over the project 8 years ago juste to maintain it alive.

Imo, the addon is not desgined to create things, juste to pull data and print it.

**Comment by Bobins666** [comment] 2020-12-09 13:09
Ahh I see, then yeah he probably doesn't play or have anything to do with addons anymore lol.

I'm happy with how it's functioning now (removing pins, even manually added pins when typing in chat), I think the addon can handle the creating pins, it's not really any different to the %loc generating the xy co ords, I might play around with it when I get some time, if I figure anything else out (testing or solution wise) I'll let you know.

**Comment by Bobins666** [comment] 2020-12-09 14:58
["%%[Ww][Pp]"] = function()
		local mapID = C_Map.GetBestMapForUnit("player")
		if mapID == nil then
			return;
		end
		local position = C_Map.GetPlayerMapPosition(mapID,"player")
		if not position then
		return
		end
		
		if C_Map.GetUserWaypointHyperlink() ~= nil then
		return "" 
		end
		if C_Map.GetUserWaypointHyperlink() == nil then
		C_Map.SetUserWaypoint(UiMapPoint.CreateFromCoordinates(mapID,position:GetXY()))
		return C_Map.GetUserWaypointHyperlink(), C_Map.ClearUserWaypoint()
		end
		end,


if pin already exists print nothing (doesn't show the failed %wp command) - does not clear it from the map

If no pin exists, create one, link it then clear it.

This is the best workaround I could find

**Comment by Djidam** [comment] 2020-12-09 15:42
Thanks for your work
I dont have time for now to test and uplopad, maybe over the weekend but no guarantees.

**Comment by Bobins666** [comment] 2020-12-09 16:31
You're welcome, that seems like the most logical solution I can come up with which is the most user friendly, I just hate seeing good addons that I use go to the bin, so hopefully this is enough to keep it from dying off

**Comment by Djidam** [comment] 2020-12-10 14:41
I know, that was the reason I took over in the first place !
I got screwed with adding this %wp command x)

**Comment by Djidam** [comment] 2020-12-10 15:17
I re-did your testing with print test. 
print "test1" for %loc and print "test2" for %wp
Regardless of what I type, I always get one print of each
So when you press enter, all functions there are executed, it's in the function after the return command that the real info is given if asked.

We can find that here : 
`local substitutions = {}
local i = 1
for k, v in pairs(subsBase) do
	substitutions[i] = { code = k, func = v }
	i = i + 1
end

sort(substitutions, function(subs1, subs2)
	return subs2.code:len() < subs1.code:len()
end)

local OrigSendChatMessage = SendChatMessage
function SendChatMessage(text, ...)
	for _, substitution in ipairs(substitutions) do
		local func = substitution.func
		text = text:gsub(substitution.code,
			type(func) == "function" and func() or func)
	end
	return OrigSendChatMessage(text, ...)
end`

I like your solutions, as you said, no pins are "created", no pins are erased (if you manually create a pin and say hello to a friend, you dont loose your pin), but pins created this way are not shown on the map.
Well, main function of this is to share your current position, it is no real use to have this pin on the map. I agree about that.
So even if its not elegant, it works.

I just added something I think could be nice.

Your solution does nothing if a pin exist. 
I prefer that, if a pin exists, it is shared.
Coz it is simplier to type %wp to share an existed pin rather than open the map and maj click the pin with chat edit box opened.
`		if C_Map.GetUserWaypointHyperlink() ~= nil then
			return C_Map.GetUserWaypointHyperlink()
		end`

What do you think of it ?

Then I will update macrotalk on curse. 
This github was created merely to share a version without the pin creations (but keeping the full version on curse)
Thanks again for your work, ill credit you on curse. 

I think i'll close this thingy in the future, curse got a nice "issues" system we could use later on.

**Comment by Djidam** [comment] 2020-12-10 15:49
Ok with the launch of SL I didnt really go to curse for awhile.
And so I juste realized the transition to overwolf was happening, and I didnt get any info about that, so my account is not there anymore, the project is tagged abandonned, but it is not abandonned at all.

I am having difficulties getting my account back.

But no worries, macrotalk was never abandonned, thanks overwolf ...

Could you post a comment over there saying project is not abndonned, just a problem with the switch to overwolf ?
Thanks

**Comment by Bobins666** [comment] 2020-12-10 17:37
I use it purely for a macro to call rares, sometimes (very rarely ) I'll manually set a pin while questing and forget about it, I'd rather not just print that pin when my macro is used i'd rather it just be left out.

I think when I tested it with linking the current manual set pin it was still doing the remove when normal text is sent thing :( maybe you could add another function for sharing the current manually set pin (not sure if they would conflict or just break and continue deleting when normal text is sent)

Yeah I'll post on curse to say it's not abandoned and it's continued to be worked on.

**Comment by Bobins666** [comment] 2020-12-10 18:03
I tested it and your way works, but I think I have a better solution, leaving my coding do nothing if %wp is called and a manual pin is set, and then add a new command purely for broadcasting a manual pin.

	["%%[Pp][Ii][Nn]"] = function()
	local mapID = C_Map.GetBestMapForUnit("player")
	if mapID == nil then
		return;
	end
	local position = C_Map.GetPlayerMapPosition(mapID,"player")
	if not position then
	return
	end
	if C_Map.GetUserWaypointHyperlink() ~= nil then
	return  C_Map.GetUserWaypointHyperlink()
	end
	end,

I just copied my previous code and changed it to %pin (cwp could also be used for current way point) and removed the function to auto set a pin if it doesn't exist, from the little testing ive done with it, it works fine (it's 4am here and I've just woken up, I messed up the [Pp] [Ii] [Nn] thing like 3 times lol

**Comment by Bobins666** [comment] 2020-12-10 23:26
to simplify the clear waypoint I made it local on line 3 (can do it with other things like getuserwaypoint.

local clearwaypoint = C_Map.ClearUserWaypoint

then I can just add clearwaypoint to my return and it does the C_Map.ClearUserWaypoint command, 

I tried for a little thismorning with making a %cwp (Clear waypoint) function but can't get it to trigger without putting %cwp into chat,
	["%%[Cc][Ww][Pp]"] = function()
	return clearwaypoint
	end

As simple as it seems I can't figure out how to get it to do the action but not print into chat, maybe you have a way to achieve it or know how to make a % command function but not message

**Comment by Djidam** [comment] 2020-12-11 08:33
Well, all the code from macrotalk are executed when you type enter in a chat.
Thik of the local subs as en array and each %loc, %wp etc as en element of this array.
Everything is set when you press enter, then, somethings can happen, or not, depending on the input text.

So you can't set a command to clear waypoint, as it will be always executed when you type enter. (I tried yesterday to be sure, and dint work)

I like the idea to seperate the manual and auto waypoints, and your problem with %pin returning sometimes as %p is normal, since everything is executed. It is when the print happens that it looks at finding %something or other things, and print the good thing.

I already added %wp in the comands, I'll add %pin. 
And when i'm back on curse I will update everything.

**Comment by Djidam** [comment] 2020-12-11 08:52
I have updated everything here and did some cleanup code.
That should work as intended.

**Comment by Bobins666** [comment] 2020-12-11 08:56
the sloppy %x function I made to clear waypoint works just fine, but it also says %x in chat, clears the pin, doesn't clear the pin when normal text is used, only when the command is called, but I don't like having it  say %x in chat so I just made a /run C_Map.ClearUserWaypoint macro and hit that before i hit my rare found macro

**Comment by Djidam** [comment] 2020-12-11 09:09
Yeah no it's normal I think ;)
I just dont get why with the local thingy that kinda works

**Comment by Djidam** [comment] 2020-12-11 09:20
Macrotalk is a chat addon so it was desgined around that, we would have to bypassed his function to type in chat in order to have it not returned something, I think.

**Comment by Djidam** [comment] 2020-12-11 09:39
Ho god, how did I not think of this

Well, that's done

```

	elseif (text == 'clear pin') then
		C_Map.ClearUserWaypoint()
		print("pin cleared")
	else
		print("Macrotalk usage : (use help for more commands)")
		print(" - TellUnit : (/tu, /whisperunit, /wu) {unit} {message}")
		print(" - Group : /group (/gr) {message}")
		print(" - Option : /opt [options] {slash command}; [options] {slash command}; ... ")
		print(" - Random command : /rndcmd [options] {command 1}\{command 2}; [options] {command 3}\{command 4}...")
		print(" - Conditional chat commands like /optsay : (/opt + chat command) [options] {text}; [options] {text}; ...")
		print(" - Random chat commands like /rndyell : (/rnd + chat command) [options] {text}; [options] {text}; ...")
		print(" - Substitutions : ")
		print("  ° Straight : %n, %z, %sz, %loc")
		print("  ° Unit : %t, %f, %m, %p, %tt")
		print("  ° Suffixes : l, c, g, r, gu, rm, h, hp, pw, pwp, ic, gn")
	end	
end
```

**Comment by Djidam** [comment] 2020-12-11 09:40
So a
` /mtk clear pin`
will do the trick

**Comment by Djidam** [comment] 2020-12-11 09:43
I can do a /clearpin or something like that but that's adding a full slash command

**Comment by Bobins666** [comment] 2020-12-11 09:43
Could add a few slash commands for it /mtk cp for short/quicker clearing lol, could probably even make it just /cp or /clear, I just hadn't really tried fiddling with that option yet.

**Comment by Djidam** [comment] 2020-12-11 09:46
I just thought it was a lot of lines of code to add just for clearing a pin, but I can see with a /cp as with a /rl, it could be great

**Comment by Djidam** [comment] 2020-12-11 09:47
Another problem with that, it can conflcts if another addon adds a command lik /cp, maybe a /mtcp to make it lees conflicted

**Comment by Bobins666** [comment] 2020-12-11 09:49
/cwp not sure if any other addon would use /cwp as a command

**Comment by Djidam** [comment] 2020-12-11 10:04
```
--[[ /clearwaypoint or /cwp]]
SLASH_CLEAR_WAYPOINT1,SLASH_CLEAR_WAYPOINT2 = '/clearwaypoint','/cwp';
SlashCmdList["CLEAR_WAYPOINT"] = function()
	if C_Map.GetUserWaypoint() ~= nil then
		C_Map.ClearUserWaypoint()
		print("waypoint cleared")
	end
end
```

**Comment by Bobins666** [comment] 2020-12-11 10:06
Works perfectly 👍

**Comment by Djidam** [comment] 2020-12-11 10:19
I think it would be a nice idea to reshare this page while my account is brought back to me.
Thanks for your message in curseforge btw.

**Comment by Bobins666** [comment] 2020-12-11 10:32
Can't hurt to reshare it, you're welcome, I was a bit saddened when I saw it was marked as abandoned, I figured I'd either try help get it back on track, or work on fixing it for my own personal use after it's abandonment, as I said I'm not exactly good at coding and know next to nothing about LUA, trial and error played a big part in it for me and a bit of googling, notepad ++ helped alot.

A little thinking outside the box and a whole lot of luck can help too lol.

**Comment by Djidam** [comment] 2020-12-11 10:38
Well you helped a lot !
It always helps having a second pair of eyes !

**Comment by Bobins666** [comment] 2020-12-12 21:43
I also threw in a "else print("No Waypoint was set.") to the clear command, I've started just using it out of habit and when I don't see a reply I'm not  sure if something broke or it didn't work :P

**Comment by Bobins666** [comment] 2020-12-12 23:46
["%%[Rr][Ll]"] = function()
	local renown 
	renown = C_CovenantSanctumUI.GetRenownLevel()
	if renown == nil then
		return;
	end
	if renown ~= nil then
	return "My Renown level is: "..renown
	end
	end

A bonus command to call renown level, while testing it, apparently even a lvl 15 toon has a renown of level 1, so the if nil doesn't need to be there, but that's okay it doesn't really matter if it returns a 1

**Comment by Djidam** [comment] 2020-12-14 15:19
Why not, too bad we can't know for a precise unit, I would have added it into suffixes.
I will tweak your thing a little, first I don't like returning sentences, I prefer only the thing we want, here it is just the renown level. 
Plus I think It will be best to first check the covenant, if 0 then no covenenant so no renown. Else you have a renown.
And so we could also have a substitution for covenant (I'll have to check the return type)

I thank you for all you did, I will close the github, I prefer having everything on curse.
If you'd like to submit suggestions, you can create tickets in curse, one ticket per thing.

**Closed** 2020-12-14 15:19 UTC
